import type { GenerationTask, TaskContentLog } from "@/types/tasks";

export const mockTasks: GenerationTask[] = [
  {
    id: "task-001",
    taskType: "generate_clusters",
    status: "in_progress",
    payload: {
      subjectId: "subj-math-9-algebra",
      count: 10,
      variantsPerCluster: 5,
      answersPerVariant: 4,
    },
    userContext:
      "Fokus auf lineare Gleichungen mit Brüchen. Schwierigkeitsgrad zwischen 3 und 6.",
    createdAt: "2024-11-26T14:25:00Z",
    startedAt: "2024-11-26T14:25:30Z",
    completedAt: null,
    delayedUntil: null,
    progressCurrent: 67,
    progressTotal: 100,
    progressMessage: "Generiere Cluster 7 von 10...",
    errorMessage: null,
    retryCount: 0,
    maxRetries: 3,
    acceptedAt: null,
    revertedAt: null,
  },
  {
    id: "task-002",
    taskType: "generate_variants",
    status: "in_progress",
    payload: {
      clusterId: "clust-quad-eq",
      count: 15,
      answersPerVariant: 4,
    },
    userContext: "Einfache quadratische Gleichungen ohne pq-Formel",
    createdAt: "2024-11-26T14:30:00Z",
    startedAt: "2024-11-26T14:30:15Z",
    completedAt: null,
    delayedUntil: null,
    progressCurrent: 23,
    progressTotal: 100,
    progressMessage: "Erstelle Variante 4 von 15...",
    errorMessage: null,
    retryCount: 0,
    maxRetries: 3,
    acceptedAt: null,
    revertedAt: null,
  },
  {
    id: "task-003",
    taskType: "generate_clusters",
    status: "completed",
    payload: {
      subjectId: "subj-math-9-algebra",
      count: 5,
      variantsPerCluster: 10,
      answersPerVariant: 4,
    },
    userContext: "Binomische Formeln für Anfänger",
    createdAt: "2024-11-26T13:00:00Z",
    startedAt: "2024-11-26T13:00:30Z",
    completedAt: "2024-11-26T13:15:45Z",
    delayedUntil: null,
    progressCurrent: 100,
    progressTotal: 100,
    progressMessage: null,
    errorMessage: null,
    retryCount: 0,
    maxRetries: 3,
    acceptedAt: null,
    revertedAt: null,
  },
  {
    id: "task-004",
    taskType: "regenerate_answers",
    status: "completed",
    payload: {
      variantId: "var-lin-001",
      count: 4,
    },
    userContext: "Bessere Distraktoren mit typischen Fehlern",
    createdAt: "2024-11-26T12:30:00Z",
    startedAt: "2024-11-26T12:30:10Z",
    completedAt: "2024-11-26T12:31:20Z",
    delayedUntil: null,
    progressCurrent: 100,
    progressTotal: 100,
    progressMessage: null,
    errorMessage: null,
    retryCount: 0,
    maxRetries: 3,
    acceptedAt: "2024-11-26T12:35:00Z",
    revertedAt: null,
  },
  {
    id: "task-005",
    taskType: "generate_variants",
    status: "failed",
    payload: {
      clusterId: "clust-grammar-cases",
      count: 20,
      answersPerVariant: 4,
    },
    userContext: null,
    createdAt: "2024-11-26T11:00:00Z",
    startedAt: "2024-11-26T11:00:15Z",
    completedAt: null,
    delayedUntil: "2024-11-26T11:05:00Z",
    progressCurrent: 35,
    progressTotal: 100,
    progressMessage: null,
    errorMessage: "LLM Service nicht verfügbar. Rate limit erreicht.",
    retryCount: 2,
    maxRetries: 3,
    acceptedAt: null,
    revertedAt: null,
  },
  {
    id: "task-006",
    taskType: "generate_clusters",
    status: "pending",
    payload: {
      subjectId: "subj-deutsch-9",
      count: 8,
      variantsPerCluster: 5,
      answersPerVariant: 4,
    },
    userContext: "Konjunktiv II mit Modalverben",
    createdAt: "2024-11-26T14:35:00Z",
    startedAt: null,
    completedAt: null,
    delayedUntil: null,
    progressCurrent: 0,
    progressTotal: 100,
    progressMessage: null,
    errorMessage: null,
    retryCount: 0,
    maxRetries: 3,
    acceptedAt: null,
    revertedAt: null,
  },
  {
    id: "task-007",
    taskType: "generate_clusters",
    status: "completed",
    payload: {
      subjectId: "subj-math-9-algebra",
      count: 3,
      variantsPerCluster: 5,
      answersPerVariant: 4,
    },
    userContext: null,
    createdAt: "2024-11-25T16:00:00Z",
    startedAt: "2024-11-25T16:00:20Z",
    completedAt: "2024-11-25T16:10:30Z",
    delayedUntil: null,
    progressCurrent: 100,
    progressTotal: 100,
    progressMessage: null,
    errorMessage: null,
    retryCount: 0,
    maxRetries: 3,
    acceptedAt: "2024-11-25T16:15:00Z",
    revertedAt: null,
  },
  {
    id: "task-008",
    taskType: "generate_variants",
    status: "cancelled",
    payload: {
      clusterId: "clust-lin-eq",
      count: 10,
      answersPerVariant: 4,
    },
    userContext: null,
    createdAt: "2024-11-25T14:00:00Z",
    startedAt: "2024-11-25T14:00:15Z",
    completedAt: null,
    delayedUntil: null,
    progressCurrent: 12,
    progressTotal: 100,
    progressMessage: null,
    errorMessage: null,
    retryCount: 0,
    maxRetries: 3,
    acceptedAt: null,
    revertedAt: null,
  },
];

export const mockTaskContentLogs: TaskContentLog[] = [
  {
    id: "log-001",
    taskId: "task-003",
    entityType: "cluster",
    entityId: "clust-binomial",
    action: "created",
    previousData: null,
    createdAt: "2024-11-26T13:05:00Z",
  },
  {
    id: "log-002",
    taskId: "task-003",
    entityType: "variant",
    entityId: "var-binom-001",
    action: "created",
    previousData: null,
    createdAt: "2024-11-26T13:06:00Z",
  },
  {
    id: "log-003",
    taskId: "task-003",
    entityType: "variant",
    entityId: "var-binom-002",
    action: "created",
    previousData: null,
    createdAt: "2024-11-26T13:07:00Z",
  },
  {
    id: "log-004",
    taskId: "task-003",
    entityType: "answer",
    entityId: "ans-binom-001-a",
    action: "created",
    previousData: null,
    createdAt: "2024-11-26T13:08:00Z",
  },
  {
    id: "log-005",
    taskId: "task-004",
    entityType: "answer",
    entityId: "ans-lin-001-a",
    action: "updated",
    previousData: JSON.stringify({ answerText: "x = 2", isCorrect: true }),
    createdAt: "2024-11-26T12:30:30Z",
  },
];

// Helper to get task by ID
export function getTaskById(id: string): GenerationTask | undefined {
  return mockTasks.find((t) => t.id === id);
}

// Helper to get logs by task ID
export function getLogsByTaskId(taskId: string): TaskContentLog[] {
  return mockTaskContentLogs.filter((l) => l.taskId === taskId);
}
